sudo: false
# sudo: enabled
language: generic

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
     - TESTING_IMAGE_NAME=unboilerplate-testing
     - REPO=us.gcr.io/unspec-utility
     - TESTING_IMAGE_QNAME=$REPO/$TESTING_IMAGE_NAME
     - TAG=${TRAVIS_COMMIT::6}
  
install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update docker-credential-gcr
  - docker-credential-gcr configure-docker
    
script: 
  - gcloud auth activate-service-account --key-file=<(base64 --decode <<< ${GCR_SERVICE_KEY})
  - docker build -t $TESTING_IMAGE_QNAME:$TAG -f tests/Dockerfile .
  - docker tag $TESTING_IMAGE_QNAME:$TAG $TESTING_IMAGE_QNAME:$TRAVIS_BRANCH
  - docker tag $TESTING_IMAGE_QNAME:$TAG $TESTING_IMAGE_QNAME:travis-${TRAVIS_BUILD_NUMBER}
  - gcloud docker -- push $TESTING_IMAGE_QNAME
 